type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/offlinehacker/xtruder-rpms/repo/fedora-%OS_VERSION%/offlinehacker-xtruder-rpms-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/infiniteloop/HeadsetControl/repo/fedora-%OS_VERSION%/infiniteloop-HeadsetControl-fedora-%OS_VERSION%.repo
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

install:
  - apcupsd
  - ckb-next
  - gnome-shell-extension-pop-shell
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-system-monitor-applet
  - gnome-shell-extension-space-bar
  - python3-pip
  - tailscale

remove:
  - firefox
  - firefox-langpacks
  - gnome-extensions-app
