name: lazuli-vrr-nvidia
description: A blingy, opinionated GNOME with an i3 feel

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 38

modules:
  - from-file: module-shared-rpm-ostree.yml

  - type: files
    files:
      - usr: /usr

  - type: bling
    install:
      - fonts
      - justfiles
      - nix-installer
      - ublue-os-wallpapers
      - ublue-update
      #- dconf-update-service


  - type: yafti             
    custom-flatpaks: # this section is optional
    - PulseAudio Volume Contro: org.pulseaudio.pavucontrol

  - type: systemd
    system:
      enable:
        - dconf-update.service
        - tailscaled.service


  - type: script
    scripts:
      - signing.sh
      - delete_residuals.sh
      - enable_vrr.sh
      - dconf-update-service.sh