name: lazuli
description: A blingy, opinionated GNOME with an i3 feel

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38

modules:
  - from-file: module-shared-rpm-ostree.yml

  - type: files
    files:
      - usr: /usr

  - type: yafti             
    custom-flatpaks: # this section is optional
    - PulseAudio Volume Contro: org.pulseaudio.pavucontrol

  - type: systemd
    system:
      enable:
        - dconf-update.service
        - tailscaled.service


  - type: script
    scripts:
      - signing.sh
      - delete_residuals.sh
      - dconf-update-service.sh